rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
# temporary fix for https://github.com/bundler/bundler/issues/2784
before_install:
  - gem update --system 2.1.11
  - gem --version
notifications:
  email:
    - tim@github.com
env:
  - PUPPET_VERSION=2.6.18
  - PUPPET_VERSION=2.7.23
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.18
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.18
